version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
services:
  prometheus:
    image: prom/prometheus:latest
    user: "1001"
    container_name: prometheus
    restart: unless-stopped
    environment:
      PROMETHEUS_PORT: 9090
      PROMETHEUS_HOST: localhost
    volumes:
      - ./promgrafnode/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./promgrafnode/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - monitoring

  promteams:
    image: quay.io/prometheusmsteams/prometheus-msteams
    container_name: promteams
    ports:
      - "2000:2000"
    environment:
      TEAMS_INCOMING_WEBHOOK_URL: ${TEAMS_HOOK_URL}
      TEMPLATE_FILE: "/tmp/card.tmpl"
    volumes:
      - /default-message-template.tmpl:/tmp/card.tmpl
  grafana:
    image: grafana/grafana:latest
    user: "1001"
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./promgrafnode/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./promgrafnode/grafana:/var/lib/grafana
    networks:
      - monitoring
  dsp-live:
    image: awaragi/prometheus-mssql-exporter
    container_name: dsp-live
    restart: unless-stopped
    environment:
      SERVER: ${DSP_SERVER}
      USERNAME: ${DSP_USERNAME}
      PASSWORD: ${DSP_PASSWORD}
    ports:
      - ${DSP_PROMETHEUS_PORT}:4000
    networks:
      - monitoring
  dsp-cnwl:
    image: awaragi/prometheus-mssql-exporter
    container_name: dsp-cnwl
    restart: unless-stopped
    environment:
      SERVER: ${CNWL_SERVER}
      PORT: ${CNWL_PORT}
      USERNAME: ${CNWL_USERNAME}
      PASSWORD: ${CNWL_PASSWORD}
    ports:
      - ${CNWL_PROMETHEUS_PORT}:4000
    networks:
      - monitoring

  dsp-nwl:
    image: awaragi/prometheus-mssql-exporter
    container_name: dsp-nwl
    restart: unless-stopped
    environment:
      SERVER: ${NWL_SERVER}
      PORT: ${NWL_PORT}
      USERNAME: ${NWL_USERNAME}
      PASSWORD: ${NWL_PASSWORD}
    ports:
      - ${NWL_PROMETHEUS_PORT}:4000
    networks:
      - monitoring

  dsp-wlt:
    image: awaragi/prometheus-mssql-exporter
    container_name: dsp-wlt
    restart: unless-stopped
    environment:
      SERVER: ${WLT_SERVER}
      USERNAME: ${WLT_USERNAME}
      PASSWORD: ${WLT_PASSWORD}
    ports:
      - ${WLT_PROMETHEUS_PORT}:4000
    networks:
      - monitoring